### ISSUE TITLE
getting error while running 

### ISSUE THREAD

**Issue by geminigeek** [zankhq/astros#13]
hi,
i am getting this error while i run yarn dev 

```
An integration attempted to inject a route that is already used in your project: "/_image" at "node_modules/@astrojs/image/dist/endpoint.js".
  This route collides with: "node_modules/astro/dist/assets/image-endpoint.js".
```

**Comment by zanhk** [comment]
@geminigeek Thanks for the segnalation, the problem was due to obslote integration with image that has been replaced in the latest astro version. This should be fixed with the latest commit.

I also added client routing, if you want to remove I added a guide how on the faq in setup.md

Let me know if you still encounter the error.

**Comment by geminigeek** [comment]
thanks , nice template
